mainsite/urls.py
from django.urls import path, include
from .views import HomeView, DemoView, DemoManView, ResourceTableView, MappingsDescr

app_name = "mainsite"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("demo", DemoView.as_view(), name="demo"),
    path("demo_man", DemoManView.as_view(), name="demo_man"),
    path("tables", ResourceTableView.as_view(), name="tables"),
    path("mappings", MappingsDescr.as_view(), name="mappings"),
]

mapping/urls.py
from django.urls import path, include
from .views import (
    ListMappingsView,
    FindInstructionView,
    InstructionTableView,
    MapAsmView,
)

app_name = "mapping"

urlpatterns = [
    path("mappings", ListMappingsView.as_view(), name="list_mappings"),
    path("find_instruction", FindInstructionView.as_view(), name="find_instruction"),
    path(
        "table_find_instruction",
        InstructionTableView.as_view(),
        name="table_find_instruction",
    ),
    path("map_asm", MapAsmView.as_view(), name="map_asm"),
]

mainsite/models.py
from django.db import models

# Create your models here.

mainsite/views.py
from collections import defaultdict
from django.views.generic.base import TemplateView
from django.utils.safestring import mark_safe
from django.conf import settings
from mapping import mappings


class HomeView(TemplateView):
    """Homepage with static content"""

    template_name = "mainsite/home.html"


class DemoView(TemplateView):
    """Palmed demo based on a mapping"""

    template_name = "mainsite/demo.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["mappings"] = list(mappings.mappings.keys())
        context["default_code"] = settings.DEMO_DEFAULT_CODE
        return context


class DemoManView(TemplateView):
    """Explain the `DemoView` view"""

    template_name = "mainsite/demo_man.html"


class MappingsDescr(TemplateView):
    """List and describes the available mappings"""

    SOURCE_STRS = {
        "palmed": mark_safe('<span class="palmed"></span>'),
        "dummy": "Dummy Source",
        "uops": mark_safe('<a href="https://uops.info/">uops.info</a>'),
    }
    template_name = "mainsite/mappings.html"

    @classmethod
    def _get_source_str(cls, source):
        return cls.SOURCE_STRS.get(source, source)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        mapping_sources = defaultdict(list)
        for name, mapping in mappings.mappings.items():
            arch_details = settings.MICROARCHITECTURES.get(mapping.details.arch, {})
            mapping_sources[mapping.details.source].append(
                {
                    "name": name,
                    "isa": mapping.details.isa,
                    "arch": mapping.details.arch,
                    "arch_title": arch_details.get("name", None),
                    "arch_href": arch_details.get("href", None),
                    "cpu": mapping.details.cpu,
                    "cpu_href": mapping.details.cpu_href,
                    "descr": mapping.details.descr,
                    "source": mapping.details.source,
                    "sourcestr": self._get_source_str(mapping.details.source),
                }
            )

        mapping_descrs = []
        try:
            palmed_mappings = mapping_sources.pop("palmed")
            mapping_descrs.append(
                (mark_safe('<span class="palmed"></span>'), palmed_mappings)
            )
        except KeyError:
            pass
        for source, mappings_of_src in mapping_sources.items():
            mapping_descrs.append((self._get_source_str(source), mappings_of_src))

        context["mappings"] = mapping_descrs
        return context


class ResourceTableView(TemplateView):
    """Resource tables -- map an instruction to a set of resources"""

    template_name = "mainsite/resource_table.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["mappings"] = list(mappings.mappings.keys())
        return context

mainsite/templates/_partials/base_js.html
<script>
  function mobile_nav_toggle() {
    $("nav > a").slideToggle(300);
  }

  $(window).resize(function () {
    if(window.innerWidth > 475) {
      $("nav > a").show(0);
    }
    else {
      $("nav > a").hide(0);
    }
  });
</script>

mainsite/templates/_partials/footer.html
{% load static %}

    <footer>
      <div id="footer_content">
        <div id="sponsors">
          <img src="{% static "img/inria.svg" %}"
               alt="INRIA"
               title="INRIA"
               />
        </div>
        <ul id="footer_links">
          <li><a href="{% url "mainsite:home" %}#team">
              <i class="fa fa-users" aria-hidden="true"></i>
              Who are we?
            </a></li>
          <li><a href="{{ research_article_ieee_url }}">
              <i class="fa fa-newspaper-o" aria-hidden="true"></i>
              {{ research_article_ieee_descr }}
            </a></li>
          <li><a href="https://gitlab.inria.fr/nderumig/palmed">
              <i class="fa fa-gitlab" aria-hidden="true"></i>
              PALMED's code
            </a></li>
          <li><a href="https://gitlab.inria.fr/CORSE/palmed-webdemo">
              <i class="fa fa-gitlab" aria-hidden="true"></i>
              This website's code
            </a></li>
        </ul>
      </div>
    </footer>

mainsite/templates/_partials/head.html
{% load static %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PALMED</title>
    <link type="text/css" rel="stylesheet" href="{% static "css/style.css" %}" />
    <link rel="icon" type="image/png" href="{% static "img/favicon32.png" %}">
    <script src="{% static "js/jquery-3.5.1.min.js" %}"></script>

mainsite/templates/_partials/header.html
{% load static %}

    <header>
      <div class="head_logo">
        <a href="{% url "mainsite:home" %}">
          <img src="{% static "img/palmed_logo.svg" %}" alt="logo" />
          <div>
            Palmed
          </div>
        </a>
      </div>

      <div id="head_main_infos">
        <span>A CPU abstract resource</span> <span>mapping model</span>
      </div>
    </header>

    <nav>
      <div id="mobile_nav_trigger" onclick="mobile_nav_toggle()">
        <i class="fa fa-bars" aria-hidden="true"></i>
        Menu
      </div>
      {% with url_name=request.resolver_match.url_name %}
      <a {% if url_name == "home" %}class="current"{% endif %} href="{% url "mainsite:home" %}" title="Homepage">
        <i class="fa fa-home" aria-hidden="true"></i>
      </a>
      <a {% if url_name == "demo" %}class="current"{% endif %} href="{% url "mainsite:demo" %}" title="Demo">
        <i class="fa fa-code" aria-hidden="true"></i> Demo
      </a>
      <a {% if url_name == "tables" %}class="current"{% endif %} href="{% url "mainsite:tables" %}" title="Resource Tables">
        <i class="fa fa-table" aria-hidden="true"></i> Tables
      </a>
      <a {% if url_name == "mappings" %}class="current"{% endif %} href="{% url "mainsite:mappings" %}" title="Available mappings">
        <i class="fa fa-map-o" aria-hidden="true"></i> Mappings
      </a>
      {% endwith %}
    </nav>

mainsite/templates/_partials/messages.html
{% if messages %}
<ul class="messages">
  {% for message in messages %}
  <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
    {{ message }}
  </li>
  {% endfor %}
</ul>
{% endif %}