mainsite/urls.py
from django.urls import path, include
from .views import HomeView, DemoView, DemoManView, ResourceTableView, MappingsDescr

app_name = "mainsite"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("demo", DemoView.as_view(), name="demo"),
    path("demo_man", DemoManView.as_view(), name="demo_man"),
    path("tables", ResourceTableView.as_view(), name="tables"),
    path("mappings", MappingsDescr.as_view(), name="mappings"),
]

mapping/urls.py
from django.urls import path, include
from .views import (
    ListMappingsView,
    FindInstructionView,
    InstructionTableView,
    MapAsmView,
)

app_name = "mapping"

urlpatterns = [
    path("mappings", ListMappingsView.as_view(), name="list_mappings"),
    path("find_instruction", FindInstructionView.as_view(), name="find_instruction"),
    path(
        "table_find_instruction",
        InstructionTableView.as_view(),
        name="table_find_instruction",
    ),
    path("map_asm", MapAsmView.as_view(), name="map_asm"),
]

mainsite/models.py
from django.db import models

# Create your models here.

mapping/models.py
from django.db import models

mainsite/views.py
from collections import defaultdict
from django.views.generic.base import TemplateView
from django.utils.safestring import mark_safe
from django.conf import settings
from mapping import mappings


class HomeView(TemplateView):
    """Homepage with static content"""

    template_name = "mainsite/home.html"


class DemoView(TemplateView):
    """Palmed demo based on a mapping"""

    template_name = "mainsite/demo.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["mappings"] = list(mappings.mappings.keys())
        context["default_code"] = settings.DEMO_DEFAULT_CODE
        return context


class DemoManView(TemplateView):
    """Explain the `DemoView` view"""

    template_name = "mainsite/demo_man.html"


class MappingsDescr(TemplateView):
    """List and describes the available mappings"""

    SOURCE_STRS = {
        "palmed": mark_safe('<span class="palmed"></span>'),
        "dummy": "Dummy Source",
        "uops": mark_safe('<a href="https://uops.info/">uops.info</a>'),
    }
    template_name = "mainsite/mappings.html"

    @classmethod
    def _get_source_str(cls, source):
        return cls.SOURCE_STRS.get(source, source)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        mapping_sources = defaultdict(list)
        for name, mapping in mappings.mappings.items():
            arch_details = settings.MICROARCHITECTURES.get(mapping.details.arch, {})
            mapping_sources[mapping.details.source].append(
                {
                    "name": name,
                    "isa": mapping.details.isa,
                    "arch": mapping.details.arch,
                    "arch_title": arch_details.get("name", None),
                    "arch_href": arch_details.get("href", None),
                    "cpu": mapping.details.cpu,
                    "cpu_href": mapping.details.cpu_href,
                    "descr": mapping.details.descr,
                    "source": mapping.details.source,
                    "sourcestr": self._get_source_str(mapping.details.source),
                }
            )

        mapping_descrs = []
        try:
            palmed_mappings = mapping_sources.pop("palmed")
            mapping_descrs.append(
                (mark_safe('<span class="palmed"></span>'), palmed_mappings)
            )
        except KeyError:
            pass
        for source, mappings_of_src in mapping_sources.items():
            mapping_descrs.append((self._get_source_str(source), mappings_of_src))

        context["mappings"] = mapping_descrs
        return context


class ResourceTableView(TemplateView):
    """Resource tables -- map an instruction to a set of resources"""

    template_name = "mainsite/resource_table.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["mappings"] = list(mappings.mappings.keys())
        return context

mapping/views.py
from functools import wraps

from django.views.generic.base import View, TemplateView, ContextMixin
from django.http import HttpResponse, JsonResponse

from . import mappings
from . import parse_asm


class JsonView(ContextMixin, View):
    """Abstract class-based view returning a JSON response"""

    class ApiError(Exception):
        def __init__(self, status, msg, is_json=False):
            self.status = status
            self.msg = msg
            self.is_json = is_json
            super().__init__()

        def __str__(self):
            return self.msg

        def http_response(self):
            if self.is_json:
                return JsonResponse(self.msg, status=self.status)
            return HttpResponse(self.msg, status=self.status)

    http_method_names = ["get", "post"]

    def get_json(self, method, context):
        """Returns the answer to this query, as json-convertible term."""
        pass

    def get(self, req, *args, **kwargs):
        try:
            r_args = req.GET
            r_args.update(kwargs)
            context = self.get_context_data(**r_args)
            return JsonResponse(self.get_json("get", context))
        except self.ApiError as exn:
            return exn.http_response()

    def post(self, req, *args, **kwargs):
        try:
            r_args = req.POST
            r_args.update(kwargs)
            context = self.get_context_data(**r_args)
            return JsonResponse(self.get_json("post", context))
        except self.ApiError as exn:
            return exn.http_response()


class MappingBoundMixin:
    """A mixin for a `JsonView` that expects a `mapping` argument."""

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            mapping_name = kwargs["mapping"][0]
        except (KeyError, IndexError) as exn:
            raise JsonView.ApiError(400, "Missing argument: mapping") from exn

        try:
            mapping = mappings.mappings[mapping_name]
        except KeyError as exn:
            raise JsonView.ApiError(
                400, "No such mapping: {}".format(mapping_name)
            ) from exn

        context["mapping"] = mapping
        return context


class ListMappingsView(JsonView):
    """List the supported mappings"""

    def get_json(self, method, context):
        return {
            name: {"arch": mapping.arch} for name, mapping in mappings.mappings.items()
        }


class FindInstructionBaseView(MappingBoundMixin, JsonView):
    """Find an instruction matching a query term"""

    allow_all = False  # Allow querying the whole mapping

    def get_instructions(self, context):
        """Get the list of matching instructions"""

        full_dataset = False

        try:
            query = context["q"][0]
        except (KeyError, IndexError) as exn:
            raise self.ApiError(400, "Missing argument: q") from exn
        query_terms = query.split()
        if not query_terms:
            if self.allow_all:
                full_dataset = True
            else:
                raise self.ApiError(400, "Bad argument: q must not be empty")
        elif not any(map(lambda x: len(x) > 2, query_terms)):
            if self.allow_all:
                full_dataset = True
            else:
                raise self.ApiError(
                    400, "Bad argument: q must contain at least two characters"
                )

        if full_dataset:
            return context["mapping"].ordered_instrs

        return list(
            filter(
                lambda x: all(map(lambda term: term in x, query_terms)),
                context["mapping"].ordered_instrs,
            )
        )


class FindInstructionView(FindInstructionBaseView):
    """Find an instruction matching a query term"""

    def get_json(self, method, context):
        return {"instructions": self.get_instructions(context)}


class InstructionTableView(FindInstructionBaseView):
    """Find instructions matching a query and return their mapping data"""

    allow_all = True

    def get_json(self, method, context):
        instructions = self.get_instructions(context)
        mapping = context["mapping"]
        instructions_data = []
        reprs_used = set()
        for instr_name in instructions:
            instr = mapping.supported_instrs[instr_name]
            instructions_data.append(
                {
                    "name": instr_name,
                    "IPC": instr.IPC_fmt,
                    "latency": instr.latency_fmt,
                    "repr": instr.repr,
                    "is_repr": instr_name == instr.repr,
                }
            )
            reprs_used.add(instr.repr)

        instr_mapping = {instr: mapping.pretty_mapping[instr] for instr in reprs_used}

        out = {
            "instructions": instructions_data,
            "mapping": instr_mapping,
            "labels": mapping.res_label,
        }
        return out


class MapAsmView(MappingBoundMixin, JsonView):
    """Takes some ASM code in argument, returns data computed from the mapping

    Parameters:
    * `mapping`: mapping slug
    * `asm`: the assembly code to analyze
    """

    http_method_names = ["post"]

    def get_json(self, method, context):
        mapping = context["mapping"]

        try:
            parser = parse_asm.AsmParser.from_string(context["asm"][0], mapping.isa)
            instrs = parser.to_pipedream_instructions()
        except parse_asm.AsmParser.ParseError as exn:
            resp = {
                "msg": exn.user_msg,
            }
            raise JsonView.ApiError(422, resp, is_json=True) from exn

        try:
            analysis = mapping.analyze_instructions(instrs)
        except mapping.BadBasicBlock as exn:
            resp = {"msg": str(exn)}
            raise JsonView.ApiError(422, resp, is_json=True) from exn
        analysis["instructions"] = instrs
        return analysis

mainsite/templates/mainsite/demo.html
{% extends "base.html" %}

{% load static %}

{% block "main_classes" %}fullsize_page{% endblock %}

{% block "extra_head" %}
<script src="{% static "js/demo.js" %}" type="text/javascript"></script>
{% endblock %}

{% block "content" %}
<div id="demo_container">
  <form id="bb_input" action="">
    {% csrf_token %}
    <div class="bb_submit_row">
      <button id="bb_eval" type="button" title="Compute (ctrl+enter)">Compute</button>
      <label for="bb_asm">Basic block input</label>
    </div>
    <textarea
      id="bb_asm"
      name="bb_asm"
      spellcheck="false"
      wrap="off"
      rows="13"
      placeholder="Try your own basic blocks here! (GAS syntax)"
    >{{ default_code }}</textarea>
    <div class="select_wrapper in_column_flex">
      <select name="mapping_slug" id="mapping_slug">
        {% for mapping in mappings %}
        <option value="{{ mapping }}">{{ mapping }}</option>
        {% endfor %}
      </select>
      <a class="helplink" href="{% url "mainsite:mappings" %}"></a>
    </div>
    <div class="helprow">
      <a href="{% url "mainsite:demo_man" %}">What is going on here?</a>
    </div>
  </form>

  <div id="demo_result">
    <div id="res_error" style="display: none">
      The assembly you provided could not be parsed. Error:
      <div id="res_error_verbatim">
      </div>
    </div>
    <div id="res_unsupported_instrs" style="display: none">
      The following instructions are not supported and have
      been ignored for this evaluation:&nbsp;<a href="{% url "mainsite:demo_man" %}#supported_instructions" class="helplink"></a>
      <ul id="res_unsupported_instrs_list">
      </ul>
    </div>
    <div id="res_stats" style="display: none;">
      <div>
        <span id="res_cycles" class="res_stat"></span>
        cycles
        <a href="{% url "mainsite:demo_man" %}#cycles" class="helplink"></a>
      </div>
      <div>
        <span id="res_ipc" class="res_stat"></span>
        <span title="Instructions Per Cycle" class="explained">IPC</span>
        <a href="{% url "mainsite:demo_man" %}#IPC" class="helplink"></a>
      </div>
    </div>
    <div id="res_resource_usage" style="display: none">
    </div>
  </div>
</div>
{% endblock %}

{% block "extra_foot" %}
<script>
  var current_asm;
  function do_update() {
    let asm = $("#bb_asm").val();
    let mapping = $("#mapping_slug").val();
    if(asm == current_asm)
      return;
    let csrf_token = $("#bb_input").children('input[name^="csrfmiddlewaretoken"]').val();
    update_demo("{% url "mapping:map_asm" %}", mapping, asm, csrf_token);
  }

  $(document).ready(function() {
      demo_hide_response();
  });
  $("#bb_eval").on('click', do_update);
  $("#bb_asm").keypress(function(event) {
    if ((event.keyCode == 10 || event.keyCode == 13) && event.ctrlKey)
      do_update();
  });
</script>
{% endblock %}

mainsite/templates/mainsite/demo_man.html
{% extends "base.html" %}

{% block "content" %}
<h1>Palmed Demo explained</h1>

<h2 id="basic_blocks">Basic blocks</h2>

<p>
A <a href="https://en.wikipedia.org/wiki/Basic_block">basic block</a> is a
block of assembly, in
<a href="https://en.wikipedia.org/wiki/GNU_Assembler">GAS</a> syntax
on this page, that contains no branches. Any branching instruction send in the
basic block input form will be <a href="#supported_instructions">ignored</a>
while plugging it into the model.
</p>

<h2 id="supported_instructions">Supported instructions</h2>

<p>For various reasons, our models are not supporting every single instruction
in the ISA. When an inputed basic block contains an unsupported instruction, it
is plainly ignored while computing the output —&nbsp;and a banner states this
clearly. Plainly ignored means that the computation will proceed as if this
instruction was not present in the output at all.</p>

<p>Here follows a list of unsupported instruction classes.</p>

<h3>Unsupported on every ISA</h3>

<ul>
  <li><em>Control flow.</em> Control flow instructions (jumps, calls, …) are
    not supported, since they are not part of basic blocks. However, this
    means that we also ignore the cost of eg. the conditional in a conditional
    jump, or the address computation.
  </li>
</ul>

<h3>Unsupported in x86-64</h3>

<ul>
  <li><em>Divisions.</em> Divisions are not supported, since their throughput
    is not easily benchmarked. Indeed, the input and output registers are
    fixed, hence creating data dependencies interfering with throughput.</li>
  <li><em>Fences.</em> Fences are by definition introducing behaviour that does
    not compose well with throughput measurements.</li>
  <li><em>Some cache control operations.</em> For the same reason, some cache
    control operations are not easily benchmarked. This includes eg.
    <span class="code">CLFSH</span>, <span class="code">PREFETCHW</span>, …
  </li>
  <li><em>x87 instructions.</em> The
    <a href="https://en.wikipedia.org/wiki/X87">x87 extension set</a> is not
    supported, since it is barely used nowadays and its microcode is generally
    sub-optimal on modern CPUs, where SSE is used instead. Additionnaly,
    composing x87 and SSE instructions in a single basic block induces a delay
    that makes model inferance difficult.
  </li>
  <li><em>AVXn, depending on the mapping.</em> Not all of our mappings support
    AVX, AVX2 and AVX512. Depending on the mapping you use, some of these
    extensions might not be available.</li>
</ul>

<h2 id="output">Output</h2>

<h3 id="throughput">Throughput measurement</h3>

<p>Our model is focused on <em>throughput</em>. This means that every insight
infered on a basic block is computed assuming:</p>

<ul>
  <li><em>No (limiting) data dependencies.</em> No instruction depends on the
    result of a previous instruction. This is equivalent to claiming that every
    instruction B depending on the result of an instruction A is "far enough"
  from A so that it has enough time to complete before B is executed.</li>

  <li><em>An infinite loop.</em> The basic block is assumed to be the body of a
    loop, executed a sufficient number of times so that it can be assumed to be
    in a steady-state.</li>
</ul>

<h3>Metrics</h3>

<p id="cycles"><em>Cycles.</em> The number of CPU cycles needed to execute the basic block
once. This number might be fractional, since we assume we are in steady state
(see above).</p>

<p id="IPC"><em>IPC (Instructions Per Cycle).</em> The number of instructions executed
per CPU cycle, on average over this basic block. This metric is relevant to HPC
experts as it describes how busy the CPU is.</p>

<h3>Resources</h3>

<p>Each abstract resource used by the given basic block is shown on this part.
Each resource can be used up to 1 per CPU cycle; thus, the Cycles metric for
this basic block is the maximal use of a resource.</p>

<p>The bottleneck resource for a given basic block is the most used one;
finding a way to alleviate the use of this resource will improve the runtime of
this basic block.</p>

<p>The use of each resource is the sum of its use by each individual
instruction. This detail can be seen by clicking on a resource in the output,
and can be used to focus the efforts on the instructions that actually
contribute significantly to a bottleneck.
{% endblock %}

mainsite/templates/mainsite/home.html
{% extends "base.html" %}

{% block "content" %}
<h1><span class="palmed"></span></h1>

<p>
<span class="palmed"></span> is a tool to establish a throughput-based
cost-model of a CPU. As a throughput-based model, dependencies between
instructions are not taken into account. It builds on top of the idea of port
mapping to perform an <span class="italic">abstract resource mapping</span> of
a processor based on a wide variety of microbenchmarks, while remaining
completely agnostic of the concrete CPU architecture, ISA, … Read about all the
details here:
</p>

<a href="{{ research_article_ieee_url }}" class="biglink">
  {{ research_article_ieee_descr }}
</a>
<a href="{{ research_article_arxiv_url }}" class="biglink">
  {{ research_article_arxiv_descr }}
</a>

<h2>Try it!</h2>

<p>Our models are presented on this website in two ways: you can either look at
the instructions tables, or play around with the model by throwing basic blocks
of assembler in, and see what comes out.</p>

<a href="{% url "mainsite:tables" %}" class="biglink">
  See the tables
</a>
<a href="{% url "mainsite:demo" %}" class="biglink">
  Try the demo
</a>

<p>Should you want to try out the tool yourself, the source code is also
available for you to look at or play with.</p>

<a href="https://gitlab.inria.fr/nderumig/palmed" class="biglink">
  Source code (Git repository)
</a>

<h2>Models</h2>

<p>On this demo website, a few different mappings are available, varying on the
architecture, CPU used, etc. Read more details about each mapping here:

<a href="{% url "mainsite:mappings" %}" class="biglink">
  Mapping details
</a>

<h2>What it does, what it does not</h2>

<p>
<span class="palmed"></span> aims at identifying the
<span class="italic">throughput-based</span> performance bottleneck of a loop
kernel, and as such, it is unable to detect <span
  class="italic">latency-based</span> performance bottlenecks.
In other words, a kernel is treated as if there were no dependency between any
two instructions and only the throughput of the used resources was taken into
account. The kernel is also treated as if it were the body of an infinite
(read: huge) loop running in steady-state.
</p>

<p>
In this abstraction, the CPU (not memory, nor cache) is modeled as a set of
abstract resources.  To be issued, an instruction must use (with a fixed ratio)
some of those resources.  This corresponds to what we call the
<span class="italic">abstract resource mapping</span> which is a dual
(conjunctive form) representation of the more known port mapping (disjunctive
form) representation. Check the details
<a href="{% url "mainsite:demo_man" %}#throughput">here</a> or in the research
article.
</p>

<h2 id="team">Who are we?</h2>

<p>
<span class="palmed"></span> is made by the
<a href="https://team.inria.fr/corse/">CORSE Inria team</a>.
It is part of the PhD of
<a href="https://team.inria.fr/corse/team-members/#nicolas-d">Nicolas
Derumigny</a> and under the supervision of
<a href="https://team.inria.fr/corse/team-members/#fabrice">Fabrice Rastello</a>.
Other contributors include
<a href="https://team.inria.fr/corse/team-members/#tbastian">Théophile Bastian</a>
(PhD student at CORSE),
<a href="https://team.inria.fr/corse/team-members/#fgruber">Fabian Gruber</a>
(former PhD student at CORSE),
and Christophe Guillon (engineer at STMicroelectronics).
</p>

<h2 id="other_projects">Related projects</h2>

<p>
<span class="palmed"></span> is not the only tool in its category! Here are a
few other related projects:
</p>

<ul>
  <li>
    <em><a href="https://uops.info/">uops.info</a></em>
    provides large data tables and port mappings for many x86
    microarchitectures.  These tables are extracted from a wide variety of
    sources, including the official documentations.
    The core contribution of uops.info is to retrieve the port mapping of
    various architectures using instrumented micro-kernels.  It requires
    hardware counters currently available only on x86 microarchitectures (Intel
    and AMD).
  </li>

  <li>
    The <em><a href="https://software.intel.com/content/www/us/en/develop/articles/intel-architecture-code-analyzer.html">Intel Architecture Code Analyzer (IACA)</a></em>
    is closely related to
    <span class="palmed"></span> in features, as it performs throughput and
    latency analysis of given basic blocks.  Unlike
    <span class="palmed"></span>, IACA both considers throughput resource usage
    and latency between dependent instructions. However, the tool is
    closed-source and is directly based off microarchitectural informations,
    strongly tying it to Intel CPUs.
  </li>

  <li>
    <em><a href="https://arxiv.org/abs/1808.07412">Ithemal</a></em>
    is a tool that provides throughput analysis
    <span class="palmed"></span> on a basic block, using a deep learning
    approach. As opposed to  <span class="palmed"></span>, Ithemal does not ignore data dependencies.
    The machine learning based approach provides a black-box costly performance model.
  </li>

  <li>
    <em><a href="https://compilers.cs.uni-saarland.de/papers/ritter_pmevo_pldi20.pdf">
      PMEvo</a></em>
    is another similar tool for computing a port mapping.
    Similarly to <span class="palmed"></span>, it does not require any specific
    hardware counter. Its approach is based on evolutionary optimization.
  </li>

  <li>
<em><a href="https://www.agner.org/optimize/">
    Agner Fog</a></em> maintains a list of instruction latencies and throughput for Intel, AMD and VIA CPUs.
As opposed to the previous projects, it does not provide any port mapping required to model the sharing of resources between instructions.
  </li>
</ul>

{% endblock %}

mainsite/templates/mainsite/mappings.html
{% extends "base.html" %}

{% block "content" %}
<h1>Mappings</h1>

<p>A mapping is obtained by running <span class="palmed"></span> on a given
machine. The output mapping may vary from run to run, depending on the
fluctuation on the result of the many individual microbenchmarks.</p>

<p>The following mappings are available for evaluation on this server.</p>

{% for source, mappings_of_src in mappings %}

<h2 class="mapping_category">Mappings from {{ source }}</h2>

<ul class="mappinglist">
{% for mapping in mappings_of_src %}
<li>
  <div class="mappingtagrow">
    <span class="mappingtag mappingname">
      {{ mapping.name }}
    </span>
    <span class="mappingtag mappingisa" title="ISA">
      {{ mapping.isa }}
    </span>
    <{% if mapping.arch_href %}a href="{{mapping.arch_href}}"{% else %}span{% endif %}
         class="mappingtag mappingarch"
         {% if mapping.arch_title %}title="{{ mapping.arch_title }}"{% endif %}
         >
      {{ mapping.arch }}
    </{% if mapping.arch_href %}a{% else %}span{% endif %}>
    <{% if mapping.cpu_href %}a href="{{ mapping.cpu_href }}"{% else %}span{% endif %}
         class="mappingtag mappingcpu"
         >
      {{ mapping.cpu }}
    </{% if mapping.cpu_href %}a{% else %}span{% endif %}>
  </div>
  {% if mapping.source != "palmed" %}
  <div class="mappingsrc">
    Mapping from {{ mapping.sourcestr }}, was not generated by
    <span class="palmed"></span>.
  </div>
  {% endif %}
  <div class="mappingdescr">{{ mapping.descr }}.</div>
</li>
{% endfor %}
</ul>
{% endfor %}

{% endblock %}

mainsite/templates/mainsite/resource_table.html
{% extends "base.html" %}
{% load static %}

{% block "main_classes" %}fullsize_page{% endblock %}

{% block "extra_head" %}
<script src="{% static "js/resource_table.js" %}" type="text/javascript"></script>
{% endblock %}

{% block "content" %}
<div class="settings_container">
  <div id="searchbar" class="form">
    <label for="searchbar_txt"><i class="fa fa-filter" aria-hidden="true"></i> </label>
    <input type="text" id="searchbar_txt" name="searchbar_txt"
                 placeholder="Filter..." />
  </div>
  <div id="mapping_selector" class="form">
    <div class="select_wrapper">
      <select name="mapping_slug" id="mapping_slug">
        {% for mapping in mappings %}
        <option value="{{ mapping }}">{{ mapping }}</option>
        {% endfor %}
      </select>
      <a class="helplink" href="{% url "mainsite:mappings" %}"></a>
    </div>
  </div>
</div>

<table class="mapping_table">
  <thead>
    <tr>
      <th>
        Instruction
        <span class="sort_btn sort_btn_name"></span>
      </th>
      <th>
        Canonical instr.
        <span class="sort_btn sort_btn_repr"></span>
      </th>
      <th>
        IPC
        <span class="sort_btn sort_btn_IPC"></span>
      </th>
      <th>
        Latency
        <span class="sort_btn sort_btn_latency"></span>
      </th>
      <th>
        Mapping
      </th>
    </tr>
  </thead>

  <tbody id="mapping_table_body">
    <tr>
      <td colspan="5">No instructions</td>
    </tr>
  </tbody>

  <tfoot>
    <tr>
      <th>
        Instruction
        <span class="sort_btn sort_btn_name"></span>
      </th>
      <th>
        Canonical instr.
        <span class="sort_btn sort_btn_repr"></span>
      </th>
      <th>
        IPC
        <span class="sort_btn sort_btn_IPC"></span>
      </th>
      <th>
        Latency
        <span class="sort_btn sort_btn_latency"></span>
      </th>
      <th>
        Mapping
      </th>
    </tr>
  </tfoot>
</table>
{% endblock %}

{% block "extra_foot" %}

<script>
  var current_mapping;

  function do_update() {
    let query = $("#searchbar_txt").val();
    let mapping = $("#mapping_slug").val();
    update_table(
      `{% url "mapping:table_find_instruction"%}?mapping=${mapping}&q=`, query
    );
  }

  function on_mapping_change() {
    let mapping = $("#mapping_slug").val();
    if(current_mapping == mapping)
      return;
    current_mapping = mapping;
    do_update();
  }

  $(document).ready(function() {
    add_sort_click_handlers();
    do_update();
  });
  $('#searchbar_txt').on('input', delay_callback(do_update, 500));
  $('#mapping_slug').on('change', delay_callback(on_mapping_change, 200));
</script>
{% endblock %}